### ISSUE TITLE
Feature Request: Electric Mixer uses Tanks

### ISSUE THREAD

**Issue by Johannason** [HaydenBelanger/assembly_line_machines#4]
Since the Simple Mixer pulls its fluid from an external tank, why not preserve that feature for the Electric Mixer?  
The Electric Mixer's internal tank is small, difficult to manage, and punishes the use of material-saving upgrades by leaving trace amounts of fluid behind which cannot be removed without breaking, replacing, and re-wiring the machine (which also empties its energy buffer).  
Using an external tank would make it easy to change fluids by just physically swapping tanks.

**Comment by Johannason** [comment]
Related bug: Electric Mixer does not begin a recipe if it contains less than one bucket of fluid, even if that recipe requires less than one bucket.  
(Example, converting enchanted book to Bottle o' Enchanting)

**Comment by HaydenBelanger** [comment]
Added the feature and also fixed the bug, will be in next version.
