### ISSUE TITLE
Some Fluids are recognized as water

### ISSUE THREAD

**Issue by Freebi85** [HaydenBelanger/assembly_line_machines#7]
Many fluids of this mod are recognized as minecraft water by other modded machines. 

-Diesel
-Gasoline
-Oil
-Liquid XP
-Condensed Void

For example oil or liquid xp can be used to make ice blocks with silent mechanisms solidifier or hydrogen in mekanisms electrolytic separator.

Cheers 🍺

**Comment by HaydenBelanger** [comment]
This will be fixed in the next version! Thank you!
